# Generated by Django 2.2.4 on 2019-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_userfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='file_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
